openapi: 3.0.1
info:
  title: BPD HB Payment Instruments API
  description: ''
  version: '1.0'
servers:
  - url: https://test.cstar.pagopa.it/bpd/hb/payment-instruments
paths:
  '/{id}':
    delete:
      summary: deletePaymentInstrumentHB
      operationId: deletepaymentinstrumenthb
      parameters:
        - name: id
          in: path
          description: 'id dello strumento di pagamento, che corrisponde al PAN (Primary Account Number) del metodo di pagamento'
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: ''
    get:
      summary: statusPaymentInstrumentHB
      operationId: statuspaymentinstrumenthb
      parameters:
        - name: id
          in: path
          description: 'id dello strumento di pagamento, che corrisponde all''hash del PAN (Primary Account Number) del metodo di pagamento'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: ''
  '/card/{id}':
    put:
      summary: enrollPaymentInstrumentHB
      description: enrollPaymentInstrumentHB
      operationId: enrollpaymentinstrumenthb
      parameters:
        - name: id
          in: path
          description: 'id dello strumento di pagamento, che corrisponde all''hash del PAN (Primary Account Number) del metodo di pagamento'
          required: true
          schema:
            type: string
      requestBody:
        description: request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentInstrumentDto'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnrollmentPaymentInstrumentResource'
        '401':
          description: ''
        '403':
          description: ''
        '500':
          description: Internal MedaCustom Server Error
  '/bpay/{id}':
    put:
      summary: enrollPaymentInstrumentHB BPay
      description: enrollPaymentInstrumentHB BancomatPay
      operationId: 5f98984972e5123d4571984b
      parameters:
        - name: id
          in: path
          description: 'id univoco dello strumento di pagamento, che corrisponde al valore cifrato della stringa “ABI+numero di cellulare”'
          required: true
          schema:
            type: string
      requestBody:
        description: request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentInstrumentBPayBody'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnrollmentPaymentInstrumentResource'
        '401':
          description: ''
        '403':
          description: ''
        '500':
          description: Internal MedaCustom Server Error
  '/satispay/{id}':
    put:
      summary: enrollPaymentInstrumentHB Satispay
      description: enrollPaymentInstrumentHB Satispay
      operationId: 5f9899f7c937adaa325c239c
      parameters:
        - name: id
          in: path
          description: id univoco dello strumento di pagamento
          required: true
          schema:
            type: string
      requestBody:
        description: request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentInstrumentSatispayBody'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnrollmentPaymentInstrumentResource'
        '401':
          description: ''
        '403':
          description: ''
        '500':
          description: Internal MedaCustom Server Error
components:
  schemas:
    PaymentInstrumentResource:
      title: PaymentInstrumentResource
      type: object
      properties:
        activationDate:
          type: string
          format: date-time
        cancellationDate:
          type: string
          format: date-time
        fiscalCode:
          type: string
        hpan:
          type: string
        status:
          enum:
            - ACTIVE
            - INACTIVE
          type: string
    EnrollmentPaymentInstrumentResource:
      title: EnrollmentPaymentInstrumentResource
      type: object
      properties:
        activationDate:
          type: string
          description: Timestamp dell’attivazione dello strumento di pagamento. FORMATO  ISO8601 yyyy-MM-ddTHH:mm:ss.SSSXXXXX
          format: date-time
    PaymentInstrumentSatispayBody:
      title: PaymentInstrumentSatispayBody
      type: object
      properties:
        fiscalCode:
          type: string
        channel:
          type: string
    PaymentInstrumentBPayBody:
      title: PaymentInstrumentBPayBody
      type: object
      properties:
        fiscalCode:
          type: string
          description: 'id dell’utente, che corrisponde al codice fiscale'
        channel:
          type: string
          description: canale che identifica univocamente l'issuer sulla piattaforma
        groupCode:
          type: string
          description: Codice ABI del gruppo a cui appartiene la banca indicata nel campo InstituteCode
        instituteCode:
          type: string
          description: Codice ABI dell’istituto dell’utente
        bank:
          type: string
          description: nome della Banca issuer
        nameHolder:
          type: string
          description: Nome offuscato del titolare conto
        surnameHolder:
          type: string
          description: Cognome offuscato del titolare conto
        phoneNumber:
          type: string
          description: Numero di cellulare del titolare conto offuscato
        serviceStatus:
          type: string
          description: stato del servizio
        infoPaymentInstrument:
          type: object
          properties:
            iban:
              type: string
              description: iban offuscato
            flagPreferredPaymentPI:
              type: boolean
              description: Se valorizzato a true indica che lo strumento a cui è associato è stato impostato come strumento di default per i pagamenti in uscita
            flagPreferredIncomingPI:
              type: boolean
              description: Se valorizzato a true indica che lo strumento a cui è associato è stato impostato come strumento di default per i pagamenti in entrata
    PaymentInstrumentDto:
      title: PaymentInstrumentDto
      type: object
      properties:
        fiscalCode:
          type: string
          description: 'id dell''utente, che corrisponde al codice fiscale'
        expireYear:
          type: integer
          description: anno di scadenza dello strumento di pagamento
        expireMonth:
          type: string
          description: mese di scadenza dello strumento di pagamento
        issuerAbiCode:
          type: string
          description: codice ABI della banca emittente carta
        brand:
          type: string
          description: 'tipo circuito (es. Visa, Mastercard)'
        holder:
          type: string
          description: titolare carta (nome e cognome)
        type:
          type: string
          description: 'tipologia carta (es. PP, DEB, CRD)'
        channel:
          type: string
          description: canale che identifica univocamente l'issuer sulla piattaforma
      example:
        fiscalCode: string
        expireYear: 0
        expireMonth: string
        issuerAbiCode: string
        brand: string
        holder: string
        type: string
        channel: string
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]